version: '3'
services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  scraper:
    build:
      context: ./myscraper
      dockerfile: Dockerfile
    depends_on:
      - database

  # webserver:
  #   build:
  #     context: ./Webserver
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5000:5000'
  #   depends_on:
  #     - database
  #     - scraper
