FROM python:3.9-slim-buster

WORKDIR /app/myscraper

RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD cd /app/myscraper && scrapy crawl sreality -s JOBDIR=crawls/sreality

